server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC
    username: user_payment
    password: payment123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

#TRACE, DEBUG, INFO, WARN, and ERROR
logging:
  level:
    root: DEBUG